### PR TITLE
corrected take/drop functions

### PR DESCRIPTION
**Pull request by ghost**
Added test cases and code fixes for two errors:

1. take/drop on complete size should be permitted
2. %ideque-drop had an error in constructing size of adjusted ideque

### CODE REVIEW

**Review by arthurgleckler — CHANGES_REQUESTED** [review]
Would you mind undoing the extraneous indentation changes?  Thanks.

**Comment by shawnw** [comment]
I just ran into this issue... any way the fix can get in the repo so I can nag downstream maintainers to update?

**Comment by arthurgleckler** [comment]
Hi, Kevin and John.  Would you please take a look at these proposed fixes
for the sample implementation in SRFI 134?

I apologize, but I didn't forward them to you when they arrived in 2017.  I
asked the original author to remove the extraneous indentation changes (to
keep the commit small), but never heard back, and the change request fell
off my radar.  I should have caught this long ago, and it may now require a
merge.

Thanks.

---------- Forwarded message ---------

**Comment by shirok** [comment]
I think I wrote that code, and both fixes are correct.

**Comment by arthurgleckler** [comment]
On Tue, Dec 22, 2020 at 12:11 PM Shiro Kawai <notifications@github.com>
wrote:

> I think I wrote that code, and both fixes are correct.
>
Thank you very much for the code and the review.

Thanks to Peter et al. (?) for the fixes, and thanks to Shawn for the
gentle prod.  Sorry about the delay.

>

**Pull request merged**
